#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countSwaps' function below.
#
# The function accepts INTEGER_ARRAY a as parameter.
#
a=[]
def countSwaps(a): 
    swapcount=0
    for i in range(0,len(a)):
        for j in range (0,len(a)-1):
            if a[j]>a[j+1]:
                a[j],a[j+1]=a[j+1],a[j];
                swapcount+=1
    print("Array is sorted in " + str(swapcount) + " swaps.")
    print("First Element: " +str(a[0]))
    print("Last Element: "+ str(a[-1]))

    
    # Write your code here

if __name__ == '__main__':
    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    countSwaps(a)
